[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow = "45MKShVdkgFWWtMj35LJsNggcsom9qGsfy2cGq8B4U5Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/samyakt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
